// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADXX0MYWWj-yxwBvDAb7nrgx2ngTJ2srg',
    appId: '1:526939468596:web:13ad1c90cba9926fcdab61',
    messagingSenderId: '526939468596',
    projectId: 'ecocharge-d39d2',
    authDomain: 'ecocharge-d39d2.firebaseapp.com',
    storageBucket: 'ecocharge-d39d2.firebasestorage.app',
    measurementId: 'G-QF4FCBVM48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8A7G6aDib_9mAdoRE_rKCfCMRocD65co',
    appId: '1:526939468596:android:e6b10af590cd7e15cdab61',
    messagingSenderId: '526939468596',
    projectId: 'ecocharge-d39d2',
    storageBucket: 'ecocharge-d39d2.firebasestorage.app',
  );
}
